-- CREATE PFI_ACCOUNT
create table pfi_account         (id_account     bigint generated by default as identity, primary key (id_account),     dt_created_at timestamp(6) not null, dt_updated_at timestamp(6) not null, vl_initial_funds numeric(15,2) not null, nm_account varchar(255));

-- CREATE PFI_TAG
create table pfi_tag             (id_tag         bigint generated by default as identity, primary key (id_tag)    ,     dt_created_at timestamp(6) not null, dt_updated_at timestamp(6) not null, fk_parent_tag bigint, ds_name varchar(255), ds_primary_hex_color varchar(10), ds_secondary_hex_color varchar(10));
alter table if exists pfi_tag         add constraint pfi_tag_fk_parent_tag_id foreign key (fk_parent_tag)      references pfi_tag;

-- CREATE PFI_TRANSFER_GROUP
create table pfi_transfer_group (id_transfer_group bigint generated by default as identity, primary key (id_transfer_group), dt_created_at timestamp(6) not null, dt_updated_at timestamp(6) not null);

-- CREATE PFI_TRANSACTION
create table pfi_transaction     (id_transaction bigint generated by default as identity, primary key (id_transaction), dt_created_at timestamp(6) not null, dt_updated_at timestamp(6) not null, dt_transaction date not null, vl_amount numeric(15,2) not null, fk_account bigint, fk_parent_transaction bigint, fk_transfer_group bigint, ds_transaction varchar(255) not null, ds_transaction_type varchar(20) not null check ((ds_transaction_type in ('INCOME','EXPENSE','TRANSFER'))));
alter table if exists pfi_transaction add constraint pfi_transaction_fk_account_id        foreign key (fk_account)            references pfi_account;
alter table if exists pfi_transaction add constraint pfi_transaction_fk_parent_transaction_id foreign key (fk_parent_transaction) references pfi_transaction;
alter table if exists pfi_transaction add constraint pfi_transaction_fk_transfer_group_id     foreign key (fk_transfer_group)     references pfi_transfer_group;

-- CREATE PFI_TRANSACTION_TAG
create table pfi_transaction_tag (fk_tag bigint not null, fk_transaction bigint not null, primary key (fk_tag, fk_transaction));
alter table if exists pfi_transaction_tag add constraint pfi_transaction_tag_fk_tag_id foreign key (fk_tag) references pfi_tag;
alter table if exists pfi_transaction_tag add constraint pfi_transaction_tag_fk_transaction_id foreign key (fk_transaction) references pfi_transaction;

